# Generated by Django 3.2.5 on 2021-07-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_image',
            new_name='photo_main',
        ),
    ]
