# Generated by Django 3.2.5 on 2021-07-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_image_book_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
