# Generated by Django 3.2.5 on 2021-07-10 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
